name: KeyboardOfMacros
keyboards:
  numpad_apps:
    path: /dev/input/by-id/usb-04d9_1203-event-kbd
    dir: ./numpad_apps
    root: index.ahk
    hotkeys:
      # NUM0 is used as shift key to launc app
      NUM6: Explorer
      NUM0NUM6: ExplorerLaunch
      $NUM_+$: Firefox
      NUM0$NUM_+$: FirefoxLaunch
      $NUM_-$: VSCode
      NUM0$NUM_-$: VSCodeLaunch 
      NUM3: Word
      NUM0NUM3: WordLaunch
      NUM2: Powerpoint
      NUM0NUM2: PowerpointLaunch
      NUM1: Excel
      NUM0NUM1: ExcelLaunch
      NUM5: Terminal
      NUM0NUM5: TerminalLaunch
      NUM9: Discord
      NUM0NUM9: DiscordLaunch
      NUM8: Premiere
      NUM0NUM8: PremiereLaunch
  logitech_g810:
    path: /dev/input/by-id/usb-Logitech_Gaming_Keyboard_G810_166A37573236-event-kbd
    dir: ./logitech_g810
    root: index.ahk
    hotkeys:
      +$ESC$: TerminatePremiere
      $ESC$: TerminateGCClient
      ^+$ESC$: RestartPremiere
      Q: DrapCopyEffects
      M: GoToMasterEffects
      W: AutoResize
      E: GraphicsCenterAlign
      R: EffectCameraBlur
      O: OpenCurrentProjectFolderEditing
      ^O: OpenCurrentProjectFolderProgramming
      +O: OpenCurrentProjectEditingApp
      ^N: GenerateNewPremiereProject
      A: RemoveUnusedMergedTracks
      G: GetGraphicsTemplate
      B: TransitionDipToBlack
      U: EffectUltraKey
      K: EffectColorKey
      T: TemplateOpenSans
      F: EffectHorizontalFlip
      I: InsertAndAutoResize
      C: OpenInAudition
      N: EffectCrop
      S: CaptureAndSave
      
      F1: GotoHomework
      +F1G: GotoHomeworkGerman
      F2: GotoYTAssets
      F3: GotoYTCoreAssets

      ^!+S: SSHPi
      ^!+T: TestIfRunning

      ^E: AutoExportAudacityAudio

      1: Trigger1 # Heading 1
      2: Trigger2 # Heading 2
      3: Trigger3 # Heading 3
      4: Trigger4 # Heading 4
      5: Trigger5 # Word Title
      L: TriggerL # Line spacing OR CurveMarkLumetri
      P: TriggerP # Set Printer Settings
      D: TriggerD # Open last Firefox donwload
addresses:
  detector: 192.168.0.100
  server:
    ipv4: 192.168.0.50
    port: 8181
perms:
  ssh: true
