name: KeyboardOfMacros
keyboards:
  logitech_g810:
    path: /dev/input/by-id/usb-Logitech_Gaming_Keyboard_G810_166A37573236-event-kbd
    dir: ./logitech_g810
    root: index.ahk
    hotkeys:
      # NOTE: A lot of remappings are to trigger function for each keys to control which hotkeys to run depending on the app
      # See index.ahk for these function for more descriptive names for what each funcion does.
      +$ESC$: TerminatePremiere
      $ESC$:
        func: TerminateGCClient
      Q: DrapCopyEffects
      W: AutoResize
      E: GraphicsCenterAlign
      O: OpenCurrentProjectFolderEditing
      ^O: OpenCurrentProjectFolderProgramming
      +O: OpenCurrentProjectEditingApp # Loads the premiere file in
      ^N: GenerateNewPremiereProject

      # Mutli
      # Function keys
      # Setting for now to only what's been written
      # Will be replaced by Trigger<key>() when time comes
      F1: GotoHomework # Open dir
      # These function allow me to go to a specific subject
      # Ideally f1 + letter would be used, but then f1 would be fired
      # Will implement a 'wait until clear' toggle in 2Keys
      # that waits for the pressed keys to clear
      # OR a modifiyer key option in config
      +F1G: GotoHomeworkGerman
      F2: GotoYTAssets # Open dir
      F3: GotoYTCoreAssets # Open dir

      # Numbers
      1: Trigger1 # Heading 1; Word, Editing; Premiere
      2: Trigger2 # Heading 2; Word, Effects; Premiere
      3: Trigger3 # Graphics; Premiere
      4: Trigger4 # Colour; Premiere
      5: Trigger5 # Audio; Premiere

      # Letters
      A: TriggerF24CA
      L: TriggerL # Line length
      P: TriggerP # PRINT
      # S: ShowSpeedDuration
      ^!+S: SSHPi
      # For testing
      ^!+T: TestIfRunning

addresses:
  detector: 192.168.0.100
  server:
    ipv4: 192.168.0.50
    port: 8181
perms:
  ssh: true
