name: KeyboardOfMacros
keyboards:
  logitech_g810:
    path: /dev/input/by-id/usb-Logitech_Gaming_Keyboard_G810_166A37573236-event-kbd
    dir: ./logitech_g810
    root: index.ahk
    hotkeys:
      +$ESC$: TerminatePremiere
      $ESC$: TerminateGCClient
      Q: DrapCopyEffects
      M: GoToMasterEffects
      W: AutoResize
      E: GraphicsCenterAlign
      O: OpenCurrentProjectFolderEditing
      ^O: OpenCurrentProjectFolderProgramming
      +O: OpenCurrentProjectEditingApp
      ^N: GenerateNewPremiereProject
      C: CurveMarkLumetri
      
      F1: GotoHomework
      +F1G: GotoHomeworkGerman
      F2: GotoYTAssets
      F3: GotoYTCoreAssets

      ^!+S: SSHPi
      ^!+T: TestIfRunning

      ^E: AutoExportAudacityAudio

      1: Trigger1
      2: Trigger2
      3: Trigger3
      4: Trigger4
      5: Trigger5
      A: TriggerF24CA
      L: TriggerL
      P: TriggerP
      D: TriggerD
addresses:
  detector: 192.168.0.100
  server:
    ipv4: 192.168.0.50
    port: 8181
perms:
  ssh: true
